### ISSUE TITLE
503

### ISSUE THREAD

**Issue by Ssummer520** [ahutsunshine/dingdong-grabber#1]
I0420 12:02:09.357310   11196 cart.go:20] 勾选购物车全选按钮失败, 错误: 您的访问已过期,请重新登录
I0420 12:02:09.588841   11196 cart.go:20] 勾选购物车全选按钮失败, 错误: 您的访问已过期,请重新登录
I0420 12:02:09.789690   11196 cart.go:20] 勾选购物车全选按钮失败, 错误: 您的访问已过期,请重新登录
E0420 12:02:09.809905   11196 cart.go:38] 获取购物车商品失败, 错误: AssertError
E0420 12:02:09.836481   11196 cart.go:38] 获取购物车商品失败, 错误: AssertError
I0420 12:02:10.011207   11196 cart.go:20] 勾选购物车全选按钮失败, 错误: 您的访问已过期,请重新登录
E0420 12:02:10.228124   11196 cart.go:38] 获取购物车商品失败, 错误: AssertError
E0420 12:02:10.339387   11196 cart.go:38] 获取购物车商品失败, 错误: AssertError
I0420 12:02:10.339387   11196 cart.go:20] 勾选购物车全选按钮失败, 错误: 您的访问已过期,请重新登录
I0420 12:02:10.413810   11196 cart.go:20] 勾选购物车全选按钮失败, 错误: 您的访问已过期,请重新登录
E0420 12:02:10.662092   11196 cart.go:38] 获取购物车商品失败, 错误: AssertError

**Comment by ahutsunshine** [comment]
@Ssummer520 你的cookie过期了
