### ISSUE TITLE
更新新版本后还是提示-3000

### ISSUE THREAD

**Issue by zric** [ahutsunshine/dingdong-grabber#12]
I0423 20:54:17.003548   70729 client.go:109] 请求结果有异常, 详情: {"success":false,"error":null,"code":-3000,"message":"","msg":"抱歉人多拥挤，请稍后再试","data":[]}
E0423 20:54:17.003590   70729 order.go:116] 获取预约时间失败, 错误: 抱歉人多拥挤，请稍后再试
I0423 20:54:17.106243   70729 cart.go:78] 更新购物车数据成功, 订单金额：229.04

**Comment by ahutsunshine** [comment]
用的最新代码嘛，按道理不应该是这样，你用叮咚买菜小程序打开预约时间看下是不是这个错，这样一般要么是签名有问题，要么被风控了，我刚刚又试了下，这样才是正常的。需要确认下是不是一直都是`获取预约时间失败, 错误: 抱歉人多拥挤，请稍后再试`, 偶尔这样没问题。
```
E0423 20:59:09.956601   70370 order.go:147] 无可选的配送时间, 原因: 当前运力紧张，今天各时段已约满，敬请谅解
I0423 20:59:10.272016   70370 cart.go:78] 更新购物车数据成功, 订单金额：77.60
I0423 20:59:10.331480   70370 cart.go:78] 更新购物车数据成功, 订单金额：77.60
```

**Comment by zric** [comment]
怎么确定是不是被风控

**Comment by zric** [comment]
我app打开是正常的

**Comment by ahutsunshine** [comment]
能给个你的cookie我来尝试下嘛，直接发我邮件吧，不要在这里发cookie，ahutsunshine@gmail.com

**Comment by zric** [comment]
发送了

**Comment by ahutsunshine** [comment]
额我居然没收到，是gmail的原因？要不发我163邮箱吧 ，ahutsunshine@163.com

**Comment by zric** [comment]
163也发送了

**Comment by ahutsunshine** [comment]
应该是gmail的原因，163收到了，我在我这里试了下，你的账号是没问题的 ，不存在你说的，你用的是最新的代码吗？
```
E0423 21:13:32.073697   70812 order.go:147] 无可选的配送时间, 原因: 当前运力紧张，今天各时段已约满，敬请谅解
I0423 21:13:32.241144   70812 cart.go:32] 勾选购物车全选按钮成功
I0423 21:13:32.564520   70812 cart.go:32] 勾选购物车全选按钮成功
E0423 21:13:32.632936   70812 order.go:147] 无可选的配送时间, 原因: 当前运力紧张，今天各时段已约满，敬请谅解
I0423 21:13:33.034457   70812 cart.go:78] 更新购物车数据成功, 订单金额：229.04
I0423 21:13:33.048454   70812 cart.go:78] 更新购物车数据成功, 订单金额：229.04
I0423 21:13:33.633552   70812 config.go:228] 获取用户信息成功, 用户: 炖羊蝎子_dHwD, id:*
E0423 21:13:33.640311   70812 order.go:147] 无可选的配送时间, 原因: 当前运力紧张，今天各时段已约满，敬请谅解
I0423 21:13:34.094135   70812 cart.go:78] 更新购物车数据成功, 订单金额：229.04
I0423 21:13:34.106823   70812 cart.go:78] 更新购物车数据成功, 订单金额：229.04
E0423 21:13:34.809094   70812 order.go:147] 无可选的配送时间, 原因: 当前运力紧张，今天各时段已约满，敬请谅解
E0423 21:13:35.196230   70812 order.go:147] 无可选的配送时间, 原因: 当前运力紧张，今天各时段已约满，敬请谅解
I0423 21:13:35.258461   70812 cart.go:78] 更新购物车数据成功, 订单金额：229.04
I0423 21:13:35.298100   70812 cart.go:78] 更新购物车数据成功, 订单金额：229.04
I0423 21:13:35.986428   70812 cart.go:32] 勾选购物车全选按钮成功
```

**Comment by zric** [comment]
对呀 我是最新的代码 
![Uploading 截屏2022-04-23 21.18.45.png…]()

**Comment by ahutsunshine** [comment]
看不到你的截图 ，按道理不应该，我和另一个使用的https://github.com/ahutsunshine/dingdong-grabber/issues/11#issuecomment-1107470812 都没问题，那只能最后一招，重启电脑试试吧😅

**Comment by zric** [comment]
我试试

**Comment by RootSir** [comment]
老哥更新后可以下单吗？还是只是购物车更新。。

**Comment by ahutsunshine** [comment]
@RootSir 必须等到早上6:00或者8:30的预约时间才行，其他时间都是不可预约的。程序的逻辑是必须有可配送时间才会提交订单，否则都是无效提交，叮咚后台也通不过的。

**Comment by RootSir** [comment]
> 

现在小程序版本更新了，现在下单的接口都找不到了，明天可能也不行了，可以找个其他城市的来验证是否可以下单 我来试试

**Comment by ahutsunshine** [comment]
你可以试试，这个代码用的还是旧版本`2.83.0`,不是最新的`2.83.1`

**Comment by zric** [comment]
重启了依旧绝了

**Comment by acio0** [comment]
windows 小程序版本升级了，没关系吧？

**Comment by ahutsunshine** [comment]
没关系，代码内置是`2.83.0`版本，下单成功后只需去 `我的`-`待支付` 支付即可

**Comment by Evergreen0726** [comment]
> 你可以试试，这个代码用的还是旧版本`2.83.0`,不是最新的

有个问题，小程序更新后抓不到包了，是什么情况

**Comment by ahutsunshine** [comment]
@Evergreen0726 E 我的电脑上还是`2.83.0`, 没研究过升级过的，我猜叮咚做了防护处理

**Comment by Highnoon8X** [comment]
请求结果有异常, 详情: {"success":false,"error":null,"code":-3000,"message":"","msg":"当前人多拥挤，请稍后尝试刷新页面","data":[]}

**Comment by coldtea07** [comment]
失败，能否不调用前边的接口，只像最后一个下单的接口发送请求呢，反正配送时间都是固定的，前边调用的越多出错的越多。

**Comment by ahutsunshine** [comment]
看起来只是最后一步提交订单有问题，只要前面有成功的，后续只是更新的过程，无论调用失败与否都不影响的。只有获取是否有预约时间影响后面是否要提交订单
```
I0424 06:06:17.811520   88424 cart.go:71] 更新购物车数据成功, 订单金额：31.70
I0424 06:06:22.304623   88424 client.go:109] 请求结果有异常, 详情: {"success":false,"error":null,"code":-3001,"message":"","msg":"","data":{}}
E0424 06:06:22.304650   88424 order.go:313] 提交订单失败, 错误: -3001 当前下单总金额：31.70
```

**Comment by ahutsunshine** [comment]
@Highnoon8X @coldtea07 今天@cpuztt 倒是用程序抢成功了 https://github.com/ahutsunshine/dingdong-grabber/issues/13#issuecomment-1107684170， 但是我失败了我没有抢到😅

**Comment by longxiaoqiu** [comment]
你好，可以询问一下，出现什么字样就表示封控了呢？在非6点和8.30这个节点可以测试出是否封控了吗？

**Comment by ahutsunshine** [comment]
很难说有什么字段被风控了，如果不是在6点和8.30这个节点上，你的请求结果一直是错误码3000，而且报错`当前人多拥挤，请稍后尝试刷新页面`, 就说明可能是两个原因导致:
1. 签名问题：未使用签名或签名算法不对
2. 风控：如果使用了最新的签名，还是报这个错，就很有可能是被风控，验证风控的方式是：你可以用微信叮咚小程序自己访问购物车下单或结算，如果api响应信息仍然是3000 `当前人多拥挤，请稍后尝试刷新页面`，那就是被风控了，如果小程序端可以访问，那就没有被风控，大概率是第一种情况。

**Comment by Highnoon8X** [comment]
> 

我在8：30分的时候用另外一个项目，抢到了一单，所以基本可以排除风控的原因了，应该还是签名的问题。

**Comment by ahutsunshine** [comment]
@Highnoon8X 不是签名的问题，现在所有抢菜项目的签名方式都是通过`sign.js`签名的。因为每隔300-500毫秒就要请求一次，很多返回结果确实是`当前人多拥挤，请稍后尝试刷新页面`, 但是细看log，其中有一些是成功的，只要有成功的就可以，后续的请求都是在不断更新购物车(去除无效卖完商品)或者预约时间.

**Comment by longxiaoqiu** [comment]
> 很难说有什么字段被风控了，如果不是在6点和8.30这个节点上，你的请求结果一直是错误码3000，而且报错`当前人多拥挤，请稍后尝试刷新页面`, 就说明可能是两个原因导致:
> 
>     1. 签名问题：未使用签名或签名算法不对
> 
>     2. 风控：如果使用了最新的签名，还是报这个错，就很有可能是被风控，验证风控的方式是：你可以用微信叮咚小程序自己访问购物车下单或结算，如果api响应信息仍然是3000 `当前人多拥挤，请稍后尝试刷新页面`，那就是被风控了，如果小程序端可以访问，那就没有被风控，大概率是第一种情况。

目前我抓了几次包，貌似都看不到maicai.api.ddxq.mobi这个域名了，有什么好办法吗？

**Comment by ahutsunshine** [comment]
@longxiaoqiu 搜搜其他的，`user/detail`, `user/address`, `allCheck`, `getMultiReserveTime`，`api.ddxq.mobi` 等，只要是和叮咚请求相关的可以都搜搜，请求头都包含Cookie或者cookie。
https://github.com/ahutsunshine/dingdong-grabber/issues/2#issuecomment-1107701097，

**Comment by longxiaoqiu** [comment]
> @longxiaoqiu 搜搜其他的，`user/detail`, `user/address`, `allCheck`, `getMultiReserveTime`，`api.ddxq.mobi` 等，只要是和叮咚请求相关的可以都搜搜，请求头都包含Cookie或者cookie，只要找到cookie就可以了 ，不需要其他参数。 [#2 (comment)](https://github.com/ahutsunshine/dingdong-grabber/issues/2#issuecomment-1107701097)

cookies我可以拿到，目前我想通过抓包的方式查看返回的状态码问题，来判断自己的账号是否发生了封控

**Comment by ahutsunshine** [comment]
那尴尬了，新版可能不太一样，还没研究过，我电脑上用的还是`2.83.0`，你可以换个默认地址比如杭州去买菜，看看是不是可以正常下单，如果可以大概率没有。

**Comment by Highnoon8X** [comment]
> * 题：未使用签名或签名算法不对
> * 风控：如果使用了最新的签名，还是报这个错

@ahutsunshine 我明天早上再试试看，就让代码一直跑，看是否可以成功。

**Comment by ahutsunshine** [comment]
@Highnoon8X 你可千万不要跑时间太久，建议就是用默认的最多跑2-3分钟就结束，否则很容易被风控封号的。

**Comment by jzhone** [comment]
我 Windows 小程序在选择界面是一直提示重新加载的，但手机小程序就一切正常

**Comment by Highnoon8X** [comment]
> @Highnoon8X 你可千万不要跑时间太久，建议就是用默认的最多跑2-3分钟就结束，否则很容易被风控封号的。

@ahutsunshine 嗯，我就用你的原版配置跑一下，有的JAVA方案太暴力，昨天我跑了一个山姆的方案，45秒，直接反馈小黑屋。

**Comment by ahutsunshine** [comment]
如果出现了无法下单被风控或者下单之后无法付款，那只能优化请求策略了：模拟真正请求，降低并发度。

**Comment by ahutsunshine** [comment]
@Highnoon8X 不知道你买成功了没，我买成功了，可惜我选的太少了，我就买了一个做试验😁

**Comment by ahutsunshine** [comment]
已兼容最新版本`2.85.2`
