### ISSUE TITLE
疑问：我填写cookie后，运行main.go后一直提示设置默认地址，默认站点和经纬度

### ISSUE THREAD

**Issue by wuxingli** [ahutsunshine/dingdong-grabber#16]
提示这个是因为对运行时间段有要求吗？（当前时间：17:20）
I0424 17:15:57.084147   19510 address.go:40] 1.默认收货地址：xxxxxxxxxxxxxxxxx, 手机号: xxxxxxxxxxxx
I0424 17:15:57.084166   19510 address.go:41] 2.该地址对应站点名称为：浦三站
I0424 17:15:57.084170   19510 address.go:42] 3.设置买菜地址经度：121.520791
I0424 17:15:57.084176   19510 address.go:43] 4.设置买菜地址纬度：31.140239

**Comment by ahutsunshine** [comment]
看下readme的说明，有两种策略: 人工策略和定时策略，默认是定时策略抢6:00和8:30，你如果手动跑的话需要在`main.go`改strategy为0

**Comment by wuxingli** [comment]
> 看下自述文件的说明，有策略：人工策略和定时策略，默认是定时策略抢夺6:00和8:30，如果你手动跑的话需要在`main.go`改策略为0

感谢大佬，自己没仔细看
