### ISSUE TITLE
请教下main.go 运行的问题

### ISSUE THREAD

**Issue by OccO3** [ahutsunshine/dingdong-grabber#17]
Go新手小白
按README里直接在VS Code运行main.go
VS Code弹出两个dependency需要安装才行
1. go-outline
2. gopls
然而开了梯子和不开梯子这两个都安装不上。。。
求大佬相助

**Comment by ahutsunshine** [comment]
为啥你们都不喜欢用Goland，这个不是挺好用的嘛 ，直接下载安装就可以跑了https://www.jetbrains.com/go/download/#section=mac，另外还需要在左上角 `Goland` - `Preference` - `Go` - `ROOT`设置Go 1.17的环境。
BTW: 我对vscode不熟😅

**Comment by hogannnn** [comment]
> 

哈哈哈本来想放在debian的机子上一直挂着跑，但是之前apt install默认装的1.13，懒得改环境了，开了一台win的机器专门装goland跑这个。
