### ISSUE TITLE
cart index找不到

### ISSUE THREAD

**Issue by Ssummer520** [ahutsunshine/dingdong-grabber#2]

**Comment by ahutsunshine** [comment]
一定要填对 `main.go`里的`cookie`和`uid`
- cookie = ""                 // 请求头部的Cookie
- uid    = ""                    // 请求头部的ddmc-uid

**Comment by Ssummer520** [comment]
我有一个好的pr不能提交抢菜成功后 微信推送提醒 没30秒提醒一次

**Comment by phybrain** [comment]
没找到cart index

**Comment by ahutsunshine** [comment]
@phybrain 只要是和叮咚请求相关的可以都搜搜，请求头都包含`Cookie`或者`cookie`
```
        UserDetail  = "https://sunquan.api.ddxq.mobi/api/v1/user/detail/"       // 获取用户信息
	Address     = "https://sunquan.api.ddxq.mobi/api/v1/user/address/"     // 获取用户默认地址， 此地址会作为买菜地址
	CartCheck   = "https://maicai.api.ddxq.mobi/cart/allCheck"             // 勾选购物车所有商品地址
	Cart        = "https://maicai.api.ddxq.mobi/cart/index"                // 获取购物车商品地址
	ReserveTime = "https://maicai.api.ddxq.mobi/order/getMultiReserveTime" // 预约送达时间地址
	CheckOrder  = "https://maicai.api.ddxq.mobi/order/checkOrder"          // 获取确认订单地址
	SubmitOrder = "https://maicai.api.ddxq.mobi/order/addNewOrder"         // 提交订单地址
```

**Comment by phybrain** [comment]
> @phybrain 只要是和叮咚请求相关的可以都搜搜，请求头都包含`Cookie`或者`cookie`
> 
> ```
>         UserDetail  = "https://sunquan.api.ddxq.mobi/api/v1/user/detail/"       // 获取用户信息
> 	Address     = "https://sunquan.api.ddxq.mobi/api/v1/user/address/"     // 获取用户默认地址， 此地址会作为买菜地址
> 	CartCheck   = "https://maicai.api.ddxq.mobi/cart/allCheck"             // 勾选购物车所有商品地址
> 	Cart        = "https://maicai.api.ddxq.mobi/cart/index"                // 获取购物车商品地址
> 	ReserveTime = "https://maicai.api.ddxq.mobi/order/getMultiReserveTime" // 预约送达时间地址
> 	CheckOrder  = "https://maicai.api.ddxq.mobi/order/checkOrder"          // 获取确认订单地址
> 	SubmitOrder = "https://maicai.api.ddxq.mobi/order/addNewOrder"         // 提交订单地址
> ```

找到了
