### ISSUE TITLE
goland怎么设置环境变量？

### ISSUE THREAD

**Issue by flychx** [ahutsunshine/dingdong-grabber#22]
GOROOT=D:\Program Files\Go #gosetup
GOPATH= #gosetup
"D:\Program Files\Go\bin\go.exe" build -o C:\Users\Administrator\AppData\Local\Temp\GoLand\___go_build_main_go.exe D:\dingdong\main.go #gosetup
go: github.com/faiface/beep@v1.1.0: Get "https://proxy.golang.org/github.com/faiface/beep/@v/v1.1.0.mod": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respo

**Comment by ahutsunshine** [comment]
这个到网上搜索一下就知道了
