### ISSUE TITLE
4月25日，报错依旧，跑了2分多，卡住了

### ISSUE THREAD

**Issue by Highnoon8X** [ahutsunshine/dingdong-grabber#23]
{"success":false,"error":null,"code":-3100,"message":"","msg":"","data":{}}
E0425 06:00:58.886537   18420 order.go:208] 获取订单确认信息失败, 错误: -3100
I0425 06:00:58.914612   18420 order.go:133] 更新配送时间成功, 配送时间段: 自动尝试可用时段
I0425 06:00:58.918625   18420 client.go:110] 请求结果有异常, 详情: {"success":false,"error":null,"code":-3100,"message":"","msg":"","data":{}}
E0425 06:00:58.918625   18420 order.go:208] 获取订单确认信息失败, 错误: -3100
I0425 06:00:58.967255   18420 client.go:110] 请求结果有异常, 详情: {"success":false,"error":null,"code":-3000,"message":"","msg":"当前人多拥挤，请稍后尝试刷新页面","data":[]}
E0425 06:00:58.967255   18420 cart.go:45] 获取购物车商品失败, 错误: 当前人多拥挤，请稍后尝试刷新页面
I0425 06:00:59.020103   18420 cart.go:28] 勾选购物车全选按钮成功
I0425 06:00:59.078769   18420 client.go:110] 请求结果有异常, 详情: {"success":false,"error":null,"code":-3000,"message":"","msg":"当前人多拥挤，请稍后尝试刷新页面","data":[]}
I0425 06:00:59.078769   18420 config.go:215] 当前人多拥挤，请稍后尝试刷新页面
I0425 06:00:59.143964   18420 client.go:110] 请求结果有异常, 详情:

**Comment by ahutsunshine** [comment]
这不是卡住了，这是为了保护不被风控或者封号，后台有个两分钟的守护线程 ，如果超过2分钟未下单成功会自动结束`未成功下单，执行2分钟自动停止`。 想要再跑的话就需要将`strategy`设置为0，重新手动运行。

**Comment by Highnoon8X** [comment]
> 这不是卡住了，这是为了保护不被风控或者封号，后台有个两分钟的守护线程 ，如果超过2分钟未下单成功会自动结束`未成功下单，执行2分钟自动停止`。 想要再跑的话就需要将`strategy`设置为0，重新手动运行。
@ahutsunshine 

- 我在7点40分的时候，用小程序进入叮咚，发现购物车会提示：“当前人多拥挤，请稍后尝试刷新页面”，在APP端就没有类似提示。我目前不能肯定，是我这个号被封控了，还是后台刷小程序cookie的人太多？自动触发的服务器保护
![微信图片_20220425074300](https://user-images.githubusercontent.com/42763247/165001728-8c3bdc90-5dbb-4d34-8adc-c2a608a0189e.jpg)
。

**Comment by ahutsunshine** [comment]
电脑端好像就是这样，我现在进去也是 `当前人多拥挤，请稍后尝试刷新页面`

**Comment by Highnoon8X** [comment]
> 

@ahutsunshine 感觉叮咚后台的风控规则又变了~~

**Comment by ahutsunshine** [comment]
如果没抢到，建议将`main.go`里`defaultMinSleepMillis`改为5000，最大`defaultMaxSleepMillis`改为15000，让程序每隔 5-15s跑一次，相当于捡漏模式，一直跑，可以试试，根据我的经验叮咚快到中午的时候还有一个时间段可以预约。

**Comment by Highnoon8X** [comment]
> 如果没抢到，建议将`main.go`里`defaultMinSleepMillis`改为5000，最大`defaultMaxSleepMillis`改为15000，让程序每隔 5-15s跑一次，相当于捡漏模式，一直跑，可以试试，根据我的经验叮咚快到中午的时候还有一个时间段可以预约。

嗯，我试试看~捡漏模式等于是抢运力。

**Comment by Highnoon8X** [comment]
> 如果没抢到，建议将`main.go`里`defaultMinSleepMillis`改为5000，最大`defaultMaxSleepMillis`改为15000，让程序每隔 5-15s跑一次，相当于捡漏模式，一直跑，可以试试，根据我的经验叮咚快到中午的时候还有一个时间段可以预约。
![c3cb06dd28a2a4307e956a41e30733c](https://user-images.githubusercontent.com/42763247/165004660-62f601ae-06ab-4bf5-a99f-98ccc40ac282.png)
感觉还是被黑号了~~

**Comment by ahutsunshine** [comment]
你这个是被风控了

**Comment by Highnoon8X** [comment]
> 你这个是被风控了

@ahutsunshine 对的，确实被封控了。换了手机号就可以下单，晚上21点我试了一下，还在小黑屋里，不知道啥时候可以出来，这个号的会员到2024年呢……叮咚人工客服都联系不上。

**Comment by poctopus** [comment]
> > 你这个是被风控了
> 
> 
> 
> @ahutsunshine 对的，确实被风控了。换了手机号就可以下单，晚上21点我试了一下，还在小黑屋里，不知道啥时候可以出来，这个号的会员到2024年呢……叮咚人工客服都联系不上。

打电话联系客服，他们会说账号有异常，但是客服没有权限解锁，只能等技术上班后处理，反正现在叮咚扯蛋的厉害，做了现在但是没给客服权限。

**Comment by ahutsunshine** [comment]
不错了你还可以联系到客服，我找了好几次都找不到

**Comment by poctopus** [comment]
> 不错了你还可以联系到客服，我找了好几次都找不到


绿卡会员会优先接入的，就是多打几次。今晚打了6-7次才有人接电话。

**Comment by poctopus** [comment]
> > 你这个是被风控了
> 
> @ahutsunshine 对的，确实被风控了。换了手机号就可以下单，晚上21点我试了一下，还在小黑屋里，不知道啥时候可以出来，这个号的会员到2024年呢……叮咚人工客服都联系不上。

会员打电话，很快会接入的，态度强硬一点，就是要下单。也许会给你一张30元的抵用券。

**Comment by ahutsunshine** [comment]
厉害了

**Comment by ahutsunshine** [comment]
@Highnoon8X @poctopus 已更新代码，兼容最新版本`2.85.2`
