### ISSUE TITLE
更新到最新版后报错

### ISSUE THREAD

**Issue by jzhone** [ahutsunshine/dingdong-grabber#24]
Build Error: go build -o c:\Users\AD\Downloads\dingdong-grabber-main\pkg\notice\__debug_bin.exe -gcflags all=-N -l .
github.com/dingdong-grabber/pkg/notice
.\music.go:13:6: Mp3 redeclared in this block
	.\mp3.go:14:6: other declaration of Mp3 (exit status 2)

**Comment by ahutsunshine** [comment]
我把名称从 `music.go`改为`mp3.go`了，你的Git在pull的时候没有自动重新命名？你看下`./pkg/notice`文件夹下是不是变成了两个`music.go`和`mp3.go`, 删除`music.go`。应该是你的Git问题。
