### ISSUE TITLE
请教 错误: -3001

### ISSUE THREAD

**Issue by zyxonhub** [ahutsunshine/dingdong-grabber#26]
![微信图片_20220425092429](https://user-images.githubusercontent.com/104043134/165006199-7d72742c-26ba-485a-90ff-1464a2644283.png)

您好，今早第一次用，显示错误-3001，是我新注册的账户问题么？

**Comment by ahutsunshine** [comment]
不是，需要不断提交多次才可以，我上午下单成功的也是这样

**Comment by zyxonhub** [comment]
> 不是，需要不断提交多次才可以，我上午下单成功的也是这样

谢谢，因为这样持续到失败，所以看看是不是哪里错了
