### ISSUE TITLE
一直显示地址，无法继续执行下去

### ISSUE THREAD

**Issue by lanefengsh** [ahutsunshine/dingdong-grabber#27]
<img width="444" alt="CleanShot 2022-04-25 at 12 43 53@2x" src="https://user-images.githubusercontent.com/49373829/165022417-ab778b2e-c9a7-4996-807f-9d1187be4a38.png">

不知道为什么一直只显示地址信息，无法继续下去，谢谢

**Comment by ahutsunshine** [comment]
你看下readme，两种策略：人工和定时，默认是定时，只抢6:00和8:30的. 人工需要在main.go里把strategy改为0再运行

**Comment by lanefengsh** [comment]
已解决，谢谢
