### ISSUE TITLE
charles 抓包pc端微信小程序不成功

### ISSUE THREAD

**Issue by le153234** [ahutsunshine/dingdong-grabber#28]
1.本人follow https://blog.csdn.net/z2181745/article/details/123002569 设置后，
1.1 首先打开Charles软件
1.2 打开PC端小程序，查看charles软件，从Sequence没有发现有maicai APP任何信息

2. 本人follow windows Charles软件设置，同样的打开PC端小程序，也没有发现Charles有maicai 信息
求助确认是我操作问题还是目前已经封掉小程序获取信息入口

**Comment by ahutsunshine** [comment]
@le153234 搜搜其他的:  `api.ddxq.mobi`, `user/detail`, `user/address`, `allCheck`, `getMultiReserveTime`等，只要是和叮咚请求相关的可以都搜搜，请求头都包含Cookie或者cookie。
https://github.com/ahutsunshine/dingdong-grabber/issues/2#issuecomment-1107701097

**Comment by le153234** [comment]
刚刚搜索了，上述关键字都没有搜到

**Comment by ahutsunshine** [comment]
@le153234 那就说明你的Charles没配置对，实在不行用iphone的教程试试？

**Comment by le153234** [comment]
没有Iphone手机，Android手机可以么？

**Comment by ahutsunshine** [comment]
安卓可以，不过我没用过安卓抓包，不能提供有效的建议。我在网上开有一个叫`packet capture`的安卓软件可以抓， 参考：https://blog.csdn.net/qq_39969226/article/details/103030361

**Comment by le153234** [comment]
我换了台电脑，新安装Charles，可以抓取出具体的数据了，非常感谢你的大力支持！
