### ISSUE TITLE
获取购物车商品失败, 错误: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by geekotaku** [ahutsunshine/dingdong-grabber#3]
E0420 14:35:33.992758    5211 client.go:60] invalid character '<' looking for beginning of value
E0420 14:35:33.992802    5211 cart.go:38] 获取购物车商品失败, 错误: invalid character '<' looking for beginning of value

**Comment by ahutsunshine** [comment]
@geekotaku 这个错没关系的，只要log里面已经出现了`更新购物车数据成功, 订单金额：`, 即代表成功，只是多次请求过程中叮咚返回了乱码，可忽略

**Comment by ahutsunshine** [comment]
经排查 ，这个是请求参数过长导致的问题，已修复  https://github.com/ahutsunshine/dingdong-grabber/commit/1b675148351590c9b099267bc7a8ea2a3086e311

**Comment by geekotaku** [comment]
已修复，thanks
