### ISSUE TITLE
4月26日，测试成功

### ISSUE THREAD

**Issue by tces1** [ahutsunshine/dingdong-grabber#30]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/9974436/165199937-ac1733bb-13ea-425b-a218-41a31b06b455.png">

有一个疑问，最新的header里面很多字段消失了，是不是脚本要更新一下。 这个是不是识别特征啊？

**Comment by ahutsunshine** [comment]
不用，程序内置的版本是2.83.0

**Comment by H1dery** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/38024275/165228762-0f1c226d-84a0-41e5-b22a-8114bf23d88d.png">
请问这个报错是什么意思，被风控了吗

**Comment by ahutsunshine** [comment]
应该不是，感觉是你这边网络的问题， `dial tcp: lookup maicai.api.ddxq.mobi: no such host`.

**Comment by tces1** [comment]
检查你的dns吧 lookup看看

**Comment by H1dery** [comment]
一开始可以 跑了一分钟左右就这样了
