### ISSUE TITLE
关于程序运行逻辑，想请教一下

### ISSUE THREAD

**Issue by Meteor0928** [ahutsunshine/dingdong-grabber#31]
代码里用到了多线程，而且一直在刷新，那有没有可能最终addNewOrder的数据存在错误？
例如，在最后提交的时候购物车商品有变化，但checkOrder数据还没有更新到

**Comment by ahutsunshine** [comment]
1. 只有拿到checkOrder的数据，才会开始addNewOrder
2. 你说的这种情况是可能的，也是无法避免的，所以checkOrder才会在不停的更新数据。这就犹如你小程序结算付款的时候显示`请返回购物车`一样，要么是没有再次获取到购物车商品要么是购物车中有的商品已经买完了。

**Comment by Meteor0928** [comment]
> 1. 只有拿到checkOrder的数据，才会开始addNewOrder
> 2. 你说的这种情况是可能的，也是无法避免的，所以checkOrder才会在不停地更新数据，addNewOrder不停地提交。这就犹如你小程序结算付款的时候显示`请返回购物车`一样，要么是没有再次获取到购物车商品，要么是购物车中有的商品已经买完了。

由于多个线程都在持续刷新，拿到checkOrder的数据之后，getCart的数据可能已经变了，而addNewOrder的数据不仅依赖于checkOrder还有getCart，所以无法保证提交的最终数据没问题

**Comment by ahutsunshine** [comment]
所以才有多个线程同时不断刷新更新数据，即使最后一次addNewOrder依赖的数据变了(比如商品数目和总价格)，那就提交失败，这是符合预期的，立即进入下一次提交即可，这时可能getCart和addNewOrder刷新已经拿到最新的数据了，否则不断循环提交，直到成功。

**Comment by ahutsunshine** [comment]
@Meteor0928 这里可以讨论策略的，如果你有更好的策略，我们可以按照更优的策略去优化。

**Comment by ahutsunshine** [comment]
> > @Meteor0928 这里可以讨论策略的，如果你有更好的策略，我们可以按照更优的策略去优化。
> 
> 还没有更好的运行策略，只能先按照目前的流程抢单了
> 
> 此外，目前也有下单无法支付的问题，也需要修正

你遇到过下单无法支付的问题吗？具体表现是什么？

**Comment by Meteor0928** [comment]
> > > @Meteor0928 这里可以讨论策略的，如果你有更好的策略，我们可以按照更优的策略去优化。
> > 
> > 
> > 还没有更好的运行策略，只能先按照目前的流程抢单了
> > 此外，目前也有下单无法支付的问题，也需要修正
> 
> 你遇到过下单无法支付的问题吗？具体表现是什么？

遇到过两次，应该是请求太频繁导致的。
提示当前下单人数过多，请稍候重试

**Comment by ahutsunshine** [comment]
1. 无论抓不抓取手机端数据都是受风控的，过于频繁的请求肯定还是会有相同的结果，如果出现这种情况适当增加请求间隔。
2. 或者换种思路，直接提供微信支付功能，购买成功后直接用调出微信支付，这种方式也可以试验下

**Comment by Meteor0928** [comment]
> * 无论抓不抓取手机端数据都是受风控的，过于频繁的请求肯定还是会有相同的结果，如果出现这种情况适当增加请求间隔。

第2种思路可以尝试下
目前下单的pay_type选择的是小程序支付

**Comment by youlv123** [comment]
确实，抢到但是无法付款

**Comment by ahutsunshine** [comment]
已更新程序兼容最新版本`2.85.2` @Meteor0928 @youlv123
