### ISSUE TITLE
请求结果有异常，code405，同时小程序也下不了单了

### ISSUE THREAD

**Issue by Evergreen0726** [ahutsunshine/dingdong-grabber#35]
请求结果有异常, 详情: {"success":null,"error":"AssertError","code":"405","message":"","msg":"","data":"-405"}

**Comment by Evergreen0726** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/22881895/165538337-5be1d621-d0b9-421a-952d-1a785e5d71ad.png">
小程序也下不了单了

**Comment by ahutsunshine** [comment]
暂时别跑了，我也是这样了😓

**Comment by kingstarcraft** [comment]
我他也是405.。。。。

**Comment by zhangduanfeng** [comment]
我也是405

**Comment by ahutsunshine** [comment]
@Evergreen0726 @kingstarcraft @zhangduanfeng 已更新代码，兼容最新版本`2.85.2`
