### ISSUE TITLE
4月28凌晨使用别的城市测试失败

### ISSUE THREAD

**Issue by haifengzuishuai** [ahutsunshine/dingdong-grabber#36]
![image](https://user-images.githubusercontent.com/46316222/165579764-f42fb884-c82f-43d2-88a9-cdf3df527089.png)

**Comment by ahutsunshine** [comment]
@haifengzuishuai 这个是被风控了，我估计你是运行的太频繁了

**Comment by pogevip** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/27748841/165660413-3c904256-434a-4b93-9b3f-8943277511c1.png">
上海这两天也没抢到

**Comment by ahutsunshine** [comment]
@haifengzuishuai @pogevip 已更新代码兼容最新版本 `2.85.2`
