### ISSUE TITLE
寻找新的解决方案

### ISSUE THREAD

**Issue by iiwen** [ahutsunshine/dingdong-grabber#37]
隔壁dingdong-helper看样子是更不了了
希望作者能帮到我们！做出最后更新！

**Comment by ahutsunshine** [comment]
@iiwen 得研究下怎么搞啊，我现在也没有什么好的思路。

**Comment by EnumaxElish** [comment]
我理解去抓银行app的包去提交是一条路。 相对更新没这么快？

**Comment by iiwen** [comment]
> @iiwen 得研究下怎么搞啊，我现在也没有什么好的思路。

我这边在研究抓支付宝和其它平台的小程序，感觉APP不通……

**Comment by iiwen** [comment]
> @iiwen 得研究下怎么搞啊，我现在也没有什么好的思路。

@ahutsunshine 明天感觉走接口路不通，我先暂时用ADB或者无障碍权限的app加上手动买，在研究中，抓包好烦人，思路就是切换城市抓接口

**Comment by ahutsunshine** [comment]
@EnumaxElish 具体思路是什么？现在新版叮咚已经不走HTTP了，Charles这种抓包没啥可以抓到的。走TCP的话怎么做，没搞过

**Comment by SnoopyFlying** [comment]
https://www.jianshu.com/p/f87512ed7b21
参考下这个。我自己用下来还可以抓到。
https://github.com/gelove/dingdong
这个似乎可以用？

**Comment by EnumaxElish** [comment]
> 

https://github.com/JannsenYang/dingdong-helper/issues/233#issuecomment-1112025625

ref this. 中行和建行app也能进叮咚的小程序页面，其中的app版本比较低，接口应该还是走http

**Comment by iiwen** [comment]
好了，我找到稳定优先级高的接口了，目前正在修改小程序
谁能解决app里支付一直弹不出来问题啊啊啊啊啊

**Comment by iiwen** [comment]
> 

要手机抓包，安卓没root好像不行啊，我果断iPhone了

**Comment by iiwen** [comment]
> 好了，我找到稳定优先级高的接口了，目前正在修改小程序 谁能解决app里支付一直弹不出来问题啊啊啊啊啊

5分钟内支付不进去哪个大佬能解决呀，或者买菜助手app解决，就是有人有方案吗，有方案的话我今晚改完程序第一时间发这位大佬

**Comment by IceCd1996** [comment]
> > 好了，我找到稳定优先级高的接口了，目前正在修改小程序 谁能解决app里支付一直弹不出来问题啊啊啊啊啊
> 
> 5分钟内支付不进去哪个大佬能解决呀，或者买菜助手app解决，就是有人有方案吗，有方案的话我今晚改完程序第一时间发这位大佬


你是显示支付失败是吗 我也是 但是我看有的issue里提到刷订单 一有订单立马停止小程序 不知道有没有用 目前我也搞定了接口 就是支付有问题

**Comment by Meteor0928** [comment]
> > > 好了，我找到稳定优先级高的接口了，目前正在修改小程序 谁能解决app里支付一直弹不出来问题啊啊啊啊啊
> > 
> > 
> > 5分钟内支付不进去哪个大佬能解决呀，或者买菜助手app解决，就是有人有方案吗，有方案的话我今晚改完程序第一时间发这位大佬
> 
> 你是显示支付失败是吗 我也是 但是我看有的issue里提到刷订单 一有订单立马停止小程序 不知道有没有用 目前我也搞定了接口 就是支付有问题

他指的应该是支付时显示下单人数过多的问题，即使下单成功了也不能支付

**Comment by ahutsunshine** [comment]
> 好了，我找到稳定优先级高的接口了，目前正在修改小程序 谁能解决app里支付一直弹不出来问题啊啊啊啊啊

@iiwen有什么稳定优先级高的接口，share下来看看。得先解决主要矛盾，当前的主要矛盾是无法下单，而不是支付，前者解决不了，后者去解决支付的问题就没什么意义。如果有更好的contribute，欢迎贡献👏🏻👏🏻

**Comment by Meteor0928** [comment]
> > 好了，我找到稳定优先级高的接口了，目前正在修改小程序 谁能解决app里支付一直弹不出来问题啊啊啊啊啊
> 
> @iiwen有什么稳定优先级高的接口，share下来看看。得先解决主要矛盾，当前的主要矛盾是无法下单，而不是支付，前者解决不了，后者去解决支付的问题就没什么意义。如果有更好的contribute，欢迎贡献👏🏻👏🏻

确实需要先解决下单问题，支付问题的话毕竟是少数

**Comment by iiwen** [comment]
获取时间好像有两个接口，有一个前面测试了不到100条，都没问题，刚刚出了success false。Alipay miniprogram都是可以抓到的，但是我在隔壁issue里面晒了一下，就405，估计我还漏了一些参数。。

**Comment by iiwen** [comment]
我现在都不敢发了，官方好像盯着，一发就405

**Comment by EnumaxElish** [comment]
那么最终还是回到本源，模拟点击了啊。

**Comment by shuangmei** [comment]
> https://github.com/gelove/dingdong
哈哈，三天后，自动解封，你被风控了，

**Comment by ahutsunshine** [comment]
新的解决方案已更新，兼容最新版本`2.85.2`。 @EnumaxElish @shuangmei @SnoopyFlying @shuangmei @IceCd1996
