### ISSUE TITLE
五一放假了，可以一起研究研究新方案，大家一起讨论啊

### ISSUE THREAD

**Issue by ahutsunshine** [ahutsunshine/dingdong-grabber#38]
五一放假了，正好有时间可以来看看有什么更好的解决方案避免被风控，目前基于HTTP的所有方案都是非常容易被风控，所以只能另寻他路了。目前思路有两种：
1. 基于最新版本TCP方案(有了解的可以comment)
2. 模拟点击

**Comment by Meteor0928** [comment]
> 五一放假了，正好有时间可以来看看有什么更好的解决方案避免被风控，目前基于HTTP的所有方案都是非常容易被风控，所以只能另寻他路了。目前思路有两种：
> 1. 基于最新版本TCP方案(有了解的可以comment)
> 2. 模拟点击

好像有人在做逆向工程了

**Comment by Meteor0928** [comment]
第一种，没搞过
第二种，有的人反馈点的快了也会风控

**Comment by EnumaxElish** [comment]
模拟点击2分钟内，高峰期，理论上很难风控吧。

**Comment by ahutsunshine** [comment]
> > 五一放假了，正好有时间可以来看看有什么更好的解决方案避免被风控，目前基于HTTP的所有方案都是非常容易被风控，所以只能另寻他路了。目前思路有两种：
> > 
> > 1. 基于最新版本TCP方案(有了解的可以comment)
> > 2. 模拟点击
> 
> 好像有人在做逆向工程了

1. 模拟点如果风控非常不科学，有的人的手速比模拟点击还快
2. 逆向工程：这个没玩过，可以研究。

**Comment by Smile1231** [comment]
我的问题就比较大了，还没跑起来，可以帮帮吗😩

**Comment by ahutsunshine** [comment]
> 我的问题就比较大了，还没跑起来，可以帮帮吗😩

新开一个issue一起看下，不要在这个解决方案的issue下讨论

**Comment by Strider1230** [comment]
模拟点击的话 点快了美团会把当前单定义为无效单，无法发起付款；叮咚目前不清楚

**Comment by zhangduanfeng** [comment]
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/46774856/166089582-7896e679-9877-4cc1-879a-ca5119422d36.png">
这是啥情况知道么？获取购物车商品失败, 错误: AssertError
I0430 11:52:29.098794   21710 client.go:127] 请求结果有异常, 详情: {"success":null,"error":"AssertError","code":"405","message":"","msg":"","data":"-405"}

**Comment by ahutsunshine** [comment]
这就是被风控了

**Comment by waynez** [comment]
原生app抓包可以解吗？听说小程序的接口高峰段都不允许下单了

**Comment by dreamparis** [comment]
如果现在电脑版的微信小程序抓包抓不到了，可以删除C:\Users\*****\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\WMPFRuntime
这个路径（可能不同的操作系统，路径略微不同，上面的路径是win7的操作系统）下的文件夹，再打开叮咚小程序就能抓包了

**Comment by ahutsunshine** [comment]
@dreamparis mac呢，没用windows

**Comment by waynez** [comment]
> 如果现在电脑版的微信小程序抓包抓不到了，可以删除C:\Users*****\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\WMPFRuntime 这个路径（可能不同的操作系统，路径略微不同，上面的路径是win7的操作系统）下的文件夹，再打开叮咚小程序就能抓包了

小程序高峰期已经完全无法下单了啊，再抓又有什么意义呢

**Comment by ahutsunshine** [comment]
@waynez 有尝试抓app端的嘛

**Comment by waynez** [comment]
app端简单抓了下，感觉好多抓不到。proxyman

**Comment by zhuProgramer** [comment]
app 可以抓，但是重放还是挂了

**Comment by waynez** [comment]
能抓到哪些接口？安卓还是ios？

**Comment by Star8Platinum** [comment]
> app 可以抓，但是重放还是挂了

重放已经不行了吗，刚想试试看。。难道只有模拟点击这条路了，暂时

**Comment by czqcs** [comment]
https://github.com/Runc2333/dingdong-helper-node/
这里有大佬研究出iOS App 的签名方法了 大佬有没有兴趣写一个go版本的

**Comment by ahutsunshine** [comment]
> https://github.com/Runc2333/dingdong-helper-node/
> 
> 这里有大佬研究出iOS App 的签名方法了 大佬有没有兴趣写一个go版本的

果然还是人多力量大，厉害👍，我今天来看看

**Comment by czqcs** [comment]
> > https://github.com/Runc2333/dingdong-helper-node/
> > 这里有大佬研究出iOS App 的签名方法了 大佬有没有兴趣写一个go版本的
> 
> 果然还是人多力量大，厉害👍，我今天来看看

`async(t, e, S) => {
    e = JSON.parse(JSON.stringify(e));
    e["private_key"] = t;
    let s = Object.keys(e).sort().map(t => {
        return t + '=' + e[t]
    }).join("&");
    let r = S.createHash("md5").update(s).digest().reduce((t, e) => {
        return t + ((e & 255).toString(16).length === 1 ? "0" + (e & 255).toString(16) : (e & 255).toString(16))
    }, "").toLowerCase();
    const a = t => {
        let e = S.createHash("md5").update(t).digest("hex").toLowerCase();
        let s = e.substr(3, 9);
        let r = e.substr(7, 20);
        let a = e.substr(1, 9);
        let o = t.split("").map(t => {
            return t.charCodeAt(0).toString(16)
        }).join("");
        let l = tools.random_string(3);
        let n = [s, r, a, o].sort().join("") + l;
        let i = S.createHash("sha1").update(n).digest("hex").toLowerCase();
        let u = i + l;
        let d = o;
        let h = e.substr(3, 26);
        let g = d + h;
        let p = g.split("").map(t => {
            return t.charCodeAt(0).toString(16)
        }).join("").substr(1, 17);
        let b = Buffer.from(u + p).toString("base64");
        let c = b + g.split("").map(t => {
            return t.charCodeAt(0).toString(16)
        }).join("").substr(48, 64) + "hexbase64";
        let m = S.createHash("md5").update(c).digest("hex").toLowerCase();
        return l + h + m
    };
    const o = t => {
        let e = S.createHash("md5").update(t).digest("hex").toLowerCase();
        let s = e.substr(5, 21);
        let r = e;
        let a = r.split("").map(t => {
            return t.charCodeAt(0).toString(16)
        }).join("").substr(1, 44);
        let o = S.createHash("md5").update(a).digest("hex").toLowerCase();
        let l = o.substr(5, 16);
        let n = o.substr(0, 16);
        let i = s + r + t;
        let u = S.createCipheriv("aes-128-cbc", l, n);
        let d = u.update(i, "utf8", "base64");
        let h = u.final("base64");
        let g = d + h;
        let p = r.substr(3, 9);
        let b = r.substr(7, 20);
        let c = r.substr(8, 9);
        let m = S.createHash("sha1").update([p, b, c, g].sort().join("")).digest("hex").toLowerCase() + tools.random_string(6);
        let C = tools.random_string(5);
        return C + m
    };
    return {
        sign: r,
        sesi: o(r),
        nars: a(r)
    }
};`

**Comment by czqcs** [comment]
> > https://github.com/Runc2333/dingdong-helper-node/
> > 这里有大佬研究出iOS App 的签名方法了 大佬有没有兴趣写一个go版本的
> 
> 果然还是人多力量大，厉害👍，我今天来看看

大佬要记得有优惠券的情况啊 隔壁已经翻车了

**Comment by ahutsunshine** [comment]
谢谢以上各位的讨论和提供了有效的参考，更新了程序。大家明天可以尝试下，有问题的话我们一起再更新。cc @waynez @EnumaxElish @dreamparis @Meteor0928 @czqcs @Star8Platinum @dreamparis @Strider1230
