### ISSUE TITLE
请求接口出现405异常是什么情况，错误: AssertError，大伙们遇到过吗？cookie是正确的

### ISSUE THREAD

**Issue by zhangduanfeng** [ahutsunshine/dingdong-grabber#40]
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/46774856/166090774-52e1872b-8f49-4a7b-8033-dadf8a393aa6.png">

**Comment by ahutsunshine** [comment]
这是被风控了，现在运行老版本的接口容易被风控

**Comment by zhangduanfeng** [comment]
> 这是被风控了，现在运行老版本的接口容易被风控

那这个应该怎么搞啊？等于说这个程序已经废了？用不了了？

**Comment by ahutsunshine** [comment]
在想其他法子拯救程序

**Comment by ahutsunshine** [comment]
@zhangduanfeng 更新了最新程序可以尝试下

**Comment by loong0306** [comment]
请问被风控一般多久可以恢复账号使用呢，谢谢
