### ISSUE TITLE
请立刻hard reset签名相关提交

### ISSUE THREAD

**Issue by Runc2333** [ahutsunshine/dingdong-grabber#43]
请立刻hard reset签名相关提交，否则由此产生的任何后果将由你自己承担。
此举并非禁止你使用相关算法，请联系我找到合适的处理方式。

**Comment by ahutsunshine** [comment]
@Runc2333 你有除了telegram其他的交流方式嘛，我的网络感觉连不上 telegram，如果有的话请将联系方式发到 `ahutsunshine@gmail.com`.

**Comment by Runc2333** [comment]
@ahutsunshine 已发送，请先hard reset签名相关提交。

**Comment by ahutsunshine** [comment]
@Runc2333 hard reset now. 没收到你的联系方式，不知道是不是gmail的问题，麻烦发我的163邮箱吧，`ahutsunshine@163.com`

**Comment by Runc2333** [comment]
@ahutsunshine 已发送，查收。

**Comment by Runc2333** [comment]
已达成共识，圆满解决。
