### ISSUE TITLE
获取 flag 参数bug

### ISSUE THREAD

**Issue by gyf19** [ahutsunshine/dingdong-grabber#44]
https://github.com/ahutsunshine/dingdong-grabber/blob/6b1296c63b2152adeb1976d6047e480b984cc727/main.go#L74

插入	flag.Parse()

**Comment by ahutsunshine** [comment]
@gyf19 thanks, 漏写了

**Comment by gyf19** [comment]
@ahutsunshine    明天抢菜，就靠咱们程序了。

**Comment by gyf19** [comment]
我关 issues
