### ISSUE TITLE
程序运行后一直在显示地址不执行抢菜

### ISSUE THREAD

**Issue by RaGNaroK0301** [ahutsunshine/dingdong-grabber#47]
先感谢作者的程序..辛苦了!

想请问下作者为何我的程序执行后一直在重复显示地址不执行抢菜呢? 

我操作时间是5/2 凌晨2点多, 已更新至最新代码, nodejs版本是16, main.go里已填入cookie, 然后我把第94行的 ""30 59 05 * *" 改成了 "30 59 01 * *" 进行测试, 结果如图
![20220502150842](https://user-images.githubusercontent.com/24788988/166198457-cd83b0ef-3632-4d11-ad9b-d8fdd459aff2.png)

是我哪里没操作正确吗?

**Comment by ahutsunshine** [comment]
不用改这个cron job时间，你看下readme，里面有几种策略，默认是定时策略，抢6:00和8:30的，strategy为1。如果想要立即跑，你需要把strategy改为0，人工策略。
