### ISSUE TITLE
项目结束了，Runc2333作者把签名服务给停用了，导致无法签名了

### ISSUE THREAD

**Issue by shuangmei** [ahutsunshine/dingdong-grabber#56]
这个项目也是采用了Runc2333作者的远程服务下载签名算法，他刚刚把签名服务器停了，所以导致无法签名了，大家可以散会了

**Comment by MataSong** [comment]
> 这个项目也是采用了Runc2333算法作者服务下载签名，他的刚刚把签名服务器了停机了，所以可以导致无法签名了，大家

这样的吗？难怪我现在执行不起来。作者人呢？

**Comment by w65467991** [comment]
> 这个项目也是采用了Runc2333作者的远程服务下载签名算法，他刚刚把签名服务器停了，所以导致无法签名了，大家可以散会了

打扰了，请问，可以把风控更新的上线吗，我看缓存的签名还是可以用的。

**Comment by w65467991** [comment]
> 这个项目也是采用了Runc2333作者的远程服务下载签名算法，他刚刚把签名服务器停了，所以导致无法签名了，大家可以散会了

真的没菜了

**Comment by ahutsunshine** [comment]
@w65467991 签名算法没问题的，但是风控这一块还是治标不治本，即使更新策略还是很容易被风控。

**Comment by EERose** [comment]
跑不起来，exit status 0xffffffff

**Comment by Manchuker1120** [comment]
目前还是不行？我看说有测试模式，但是我看config里面没有啊。

**Comment by Yushenbo** [comment]
> 

签名服务器是停了

![image](https://user-images.githubusercontent.com/3889162/166640638-dadf2bd9-c38a-42cf-883c-3c49f763fec0.png)

**Comment by Curl-Li** [comment]
ios逆向找到了签名算法，但是风控越来越严格，没法搞了，下了单也可能无法付款

**Comment by MataSong** [comment]
@Curl-Li 别管那么多了 先上吧 铁铁，我号多。 哈哈哈

**Comment by ahutsunshine** [comment]
更新了签名，项目还在测试，将尽可能降低风控风险，但这些都是治标不治本，这个项目就当参考吧

**Comment by zen1f** [comment]
> @Curl-Li 别管那么多了 先上吧 铁铁，我号多。 哈哈哈

我也想上啊，没时间搞
