### ISSUE TITLE
vscode

### ISSUE THREAD

**Issue by chenshi1324** [ahutsunshine/dingdong-grabber#8]
请问一下 vsocde咋运行啊 有具体流程吗 实在是不会弄 go环境装好了 但是不会再vscode运行  家里菜和米都没了 只剩面条了...

**Comment by ahutsunshine** [comment]
https://www.jetbrains.com/go/download/#section=mac 用这个Goland吧，下载好运行 `make vendor` (实际上是 `go mod tidy`, `go  mod vendor`)下载依赖包，然后运行`main.go`

**Comment by Highnoon8X** [comment]
终端里，键入go run main.go
