### ISSUE TITLE
请求结果有异常，抱歉人多拥挤，请稍后再试

### ISSUE THREAD

**Issue by Evergreen0726** [ahutsunshine/dingdong-grabber#9]
4.22上午，测试时无法获取预约时间，猜测是checkorder request出问题，程序反复报错：
cart.go:74 更新购物车数据成功, 订单金额：49.90
client.go:90 请求结果有异常, 详情: {"success":false,"error":null,"code":-3000,"message":"","msg":"抱歉人多拥挤，请稍后再试","data":[]}
order.go:107 获取预约时间失败, 错误: 抱歉人多拥挤，请稍后再试

与此同时手机上测试没有拥挤问题，只是无可选的配送时间

**Comment by ahutsunshine** [comment]
可能叮咚更新了什么，今天下班看下fix下，工作活太多

**Comment by Evergreen0726** [comment]
应该是GetMultiReserveTime request

**Comment by ahutsunshine** [comment]
@Evergreen0726 `GetMultiReserveTime`拥挤这个是正常的，事实上叮咚很多流量都到了获取预约时间上了，你可以看下log，很多次请求后是可以获取到预约时间的

**Comment by Evergreen0726** [comment]
@

> @Evergreen0726 `GetMultiReserveTime`拥挤这个是正常的，事实上叮咚很多流量都到了获取预约时间上了，你可以看下log，很多次请求后是可以获取到预约时间的

今天一直尝试，还没成功获取到过，但手机上一次就能获取到。

**Comment by ahutsunshine** [comment]
这个需要在6:00和8:30的尝试才是有效的，今天我试了是work的，尽管出现了多次拥挤报错

**Comment by Evergreen0726** [comment]
> 这个需要在6:00和8:30的尝试才是有效的，今天我试了是work的，尽管出现了多次拥挤报错

设置strategy 0: 人工策略 就不会限制6:00和8:30吧？

**Comment by mhqschen** [comment]
> @
> 
> > @Evergreen0726 `GetMultiReserveTime`拥挤这个是正常的，事实上叮咚很多流量都到了获取预约时间上了，你可以看下log，很多次请求后是可以获取到预约时间的
> 
> 今天一直尝试，还没成功获取到过，但手机上一次就能获取到。

我用curl监控运力也遇到了这个问题。叮咚后台应该升级过了。原来的curl被识别后就会拥挤，然后就会失效，表现为永远是拥挤。你重新抓包后那个curl就正常了，知道再次被识别到。
昨天之前识别到后是直接限流，手机上也获取不到运力，直到解封，那时候这个curl也恢复了。
我把检测时间拉长到25~45秒都会被识别，目前不知道怎么破解这个。

**Comment by ahutsunshine** [comment]
不限制，但是不在这两个时间段的话获取GetMultiReserveTime，点开微信小程序购物车 - 结算 - 请选择送达时间，显示的信息就是 `前方拥挤，请稍后再试`

**Comment by Evergreen0726** [comment]
> 不限制，但是不在这两个时间段的话获取GetMultiReserveTime，点开微信小程序购物车 - 结算 - 请选择送达时间，显示的信息就是 `前方拥挤，请稍后再试`

小程序上也可以获取到，不会拥挤

**Comment by Evergreen0726** [comment]
最新情况，api和app version更新到了9.50.1和2.85.1

**Comment by ahutsunshine** [comment]
@Evergreen0726 看来后台是启用签名了，我尝试了下用Charles正常抓到的请求curl or Postman是work的，但是如果去除`nars`和`sesi`签名参数，则会报`人多拥挤`错误
```
{
    "msg": "抱歉人多拥挤，请稍后再试",
    "code": -3000,
    "timestamp": "2022-04-22 22:31:02",
    "success": false,
    "exec_time": null
}
````

**Comment by geekotaku** [comment]
strategy 0 人工策略，循环时间改长了，开了一会儿，报405错误了，账号被封禁了12小时😭

**Comment by ahutsunshine** [comment]
这个肯定是可预见的，所以才有2分钟的守护线程避免长时间抢菜被封

**Comment by ahutsunshine** [comment]
@Evergreen0726 @mhqschen @geekotaku 签名算法更新了，现在可以了
